import { Metadata } from "next";
import { auth } from "@/authentication/auth.config";
import { redirect } from "next/navigation";
import { SideBar } from "@/components/UI";
export async function generateMetadata(): Promise<Metadata> {
  const session = await auth();
  const name: string = session.user.name ?? "";
  return {
    title: name,
    description: "Generated by create next app",
  }
}

async function ProtectedLayout({
  children
}: {
  children: React.ReactNode
}) {
  const session = await auth();
  if (!session) {
    redirect("/api/auth/signin");
  }
  return (
    <div className="min-h-screen max-w-[1440px] mx-auto flex ">
      <SideBar />

      <main className="flex-1 overflow-hidden">
        {children}
      </main>
    </div>
  )
}

export default ProtectedLayout