import { Metadata } from "next";
import { auth } from "@/authentication/auth.config";
import { redirect } from "next/navigation";
import { SideBar } from "@/components/UI";
import { checkIsAuthenticated } from "@/libs/auth/checkIsAuthenticated";
export async function generateMetadata(): Promise<Metadata> {
  const session = await auth();
  const name: string | null | undefined = session ? session!.user!.name : "TTL - Store";
  return {
    title: name,
    description: "Generated by create next app",
  }
}

async function ProtectedLayout({
  children
}: {
  children: React.ReactNode
}) {
  const isAuthenticated = await checkIsAuthenticated();
  if (!isAuthenticated) {
    redirect("/auth/signin");
  }
  return (
    <div className="min-h-screen max-w-[1440px] mx-auto flex ">
      <SideBar />

      <main className="flex-1 overflow-hidden">
        {children}
      </main>
    </div>
  )
}

export default ProtectedLayout